### ISSUE TITLE
PPDM Deploy scripts hangs on TELEMETRY_SETTING

### ISSUE THREAD

**Issue by Ainillia** [dell/powerprotect-data-manager#12]
Hello,

The PPDM Deployment script hangs on TELEMETRY_SETTING : 

---> TELEMETRY EULA accepted
->The call PUT https://xxx.xxx.xxx.xxx:8443/api/v2/common-settings/TELEMETRY_SETTING failed with exception:400 Client Error:  for url: https://xxx.xxx.xxx.xxx:8443/api/v2/common-settings/TELEMETRY_SETTING
Traceback (most recent call last):
  File "PPDM_DEPLOY.py", line 853, in <module>
    main()
  File "PPDM_DEPLOY.py", line 800, in main
    config_auto_support(ppdmUri, token)
  File "PPDM_DEPLOY.py", line 580, in config_auto_support
    response = init_rest_call("PUT", ppdmUri, token, payload)
  File "PPDM_DEPLOY.py", line 292, in init_rest_call
    f"\033[91m\033[1m->Failed to query {uri}, code: {response.status_code}, body: {response.text}\033[39m"
Exception: ->Failed to query https://xxx.xxx.xxx.xxx:8443/api/v2/common-settings/TELEMETRY_SETTING, code: 400, body: {"code":400,"path":"/api/v2/common-settings/TELEMETRY_SETTING","reason":"Object instance has properties which are not allowed by the schema: ['_links'].","timestamp":1717159822231}

**Script version** : 3 (January 2024)
**PPDM Deployed** : 19.16.0-15
**Python** : 3.6

Previous deployments on 19.14 & 19.15 were working. Maybe it has to do with strict API, seeing "not allowed by schema".

Thanks for your help.

**Comment by IdanKen** [comment]
Thanks for the feedback @Ainillia, fixed in v4:
https://github.com/dell/powerprotect-data-manager/blob/PPDM-main/Python/ppdm_deploy/ppdm_deploy.py
